### ISSUE TITLE
xfov: Zooming stops working if you switch weapon while toggle_zoom

### ISSUE THREAD

**Issue by Andrej730** [jackharpr/sourcemod-hl2dm#2]
The bug I've found - if you switch weapon while toggle_zoom you won't be able zoom again because `giClientZoom[iClient]` will keep the value `ZOOM_TOGL` (because the plugin expects you to exit toggle_zoom with another `toggle_zoom` command not the weapon switch).

The way I solved this problem for me is I've hooked to the SDKHook_WeaponSwitchPost (SDKHooks required).
```SourcePawn
public void OnClientPostAdminCheck(int iClient)
{
    SDKHook(iClient, SDKHook_WeaponSwitchPost, OnWeaponSwitch);
}
```

Hook code:
```SourcePawn
public Action:OnWeaponSwitch(int iClient, int iWeapon)
{
    if (g_FOVState[iClient] == ZOOM_TOGL)
        g_FOVState[iClient] = ZOOM_NONE;
}
```

Not sure if there is any other way to switch from toggle_zoom without `toggle_zoom` besides switching weapons. If there's more maybe it's a good idea to hook somehow to the state of zooming by some other way, not by processing all pressed keys with `OnPlayerRunCmd`. If it's not the case everything should be fine.

**Comment by utharper** [comment]
afe0ee8

**Comment by utharper** [comment]
99f972b
